server.port=8081

spring.profiles.active=produccion

spring.jpa.show-sql=true

simulador.activo=false

api.openweathermap.key=${OPENWEATHERMAP_KEY:API_KEY_AQUI}
api.mapbox.key=${MAPBOX_KEY:API_KEY_AQUI}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

