server.port=8080

# MQTT
mqtt.broker=tcp://192.168.100.173:1883
mqtt.usuario=itt363-grupo2
mqtt.clave=knDH2P6N4w9g
mqtt.topic=/itt363-grupo2/+/sensores/#

# PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.34.192:5432/EstacionMetereologica
spring.datasource.username=java_user
spring.datasource.password=Daury201
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true